-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 16:46:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agricultores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agricultores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CAF` VARCHAR(45) BINARY NOT NULL,
  `CPF` VARCHAR(11) BINARY NOT NULL,
  `local` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `subtipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ofertas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produtos_id` INT NOT NULL,
  `agricultores_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ofertas_produtos_idx` (`produtos_id` ASC) VISIBLE,
  INDEX `fk_ofertas_agricultores1_idx` (`agricultores_id` ASC) VISIBLE,
  CONSTRAINT `fk_ofertas_produtos`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `mydb`.`produtos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ofertas_agricultores1`
    FOREIGN KEY (`agricultores_id`)
    REFERENCES `mydb`.`agricultores` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instituicoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`editais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editais` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `instituicoes_id` INT NOT NULL,
  `detalhes` VARCHAR(400) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_editais_instituicoes1_idx` (`instituicoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_editais_instituicoes1`
    FOREIGN KEY (`instituicoes_id`)
    REFERENCES `mydb`.`instituicoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documentos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requisitos` (
  `documentos_id` INT NOT NULL,
  `editais_id` INT NOT NULL,
  PRIMARY KEY (`documentos_id`, `editais_id`),
  INDEX `fk_documentos_has_editais_editais1_idx` (`editais_id` ASC) VISIBLE,
  INDEX `fk_documentos_has_editais_documentos1_idx` (`documentos_id` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_has_editais_documentos1`
    FOREIGN KEY (`documentos_id`)
    REFERENCES `mydb`.`documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documentos_has_editais_editais1`
    FOREIGN KEY (`editais_id`)
    REFERENCES `mydb`.`editais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
