-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 01:45:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agrofam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agrofam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agrofam` DEFAULT CHARACTER SET utf8 ;
USE `agrofam` ;

-- -----------------------------------------------------
-- Table `agrofam`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`uf` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`localidades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `uf_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_localidades_uf1_idx` (`uf_id` ASC),
  CONSTRAINT `fk_localidades_uf1`
    FOREIGN KEY (`uf_id`)
    REFERENCES `agrofam`.`uf` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`agricultores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`agricultores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CAF` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `CPF` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `localidades_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agricultores_localidades1_idx` (`localidades_id` ASC),
  CONSTRAINT `fk_agricultores_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `agrofam`.`localidades` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`arquivos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `agricultores_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_arquivos_agricultores1_idx` (`agricultores_id` ASC),
  CONSTRAINT `fk_arquivos_agricultores1`
    FOREIGN KEY (`agricultores_id`)
    REFERENCES `agrofam`.`agricultores` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`instituicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`instituicoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `localidades_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_instituicoes_localidades1_idx` (`localidades_id` ASC),
  CONSTRAINT `fk_instituicoes_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `agrofam`.`localidades` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`editais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`editais` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `instituicoes_id` INT(11) NOT NULL,
  `descricao` VARCHAR(240) NOT NULL,
  `dataIni` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `link` VARCHAR(8000) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_editais_instituicoes1_idx` (`instituicoes_id` ASC),
  CONSTRAINT `fk_editais_instituicoes1`
    FOREIGN KEY (`instituicoes_id`)
    REFERENCES `agrofam`.`instituicoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`subtipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`subtipos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`produtos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `subtipos_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produtos_subtipo1_idx` (`subtipos_id` ASC),
  CONSTRAINT `fk_produtos_subtipo1`
    FOREIGN KEY (`subtipos_id`)
    REFERENCES `agrofam`.`subtipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`demandas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`demandas` (
  `editais_id` INT(11) NOT NULL,
  `produtos_id` INT(11) NOT NULL,
  PRIMARY KEY (`editais_id`, `produtos_id`),
  INDEX `fk_editais_has_produtos_produtos1_idx` (`produtos_id` ASC),
  INDEX `fk_editais_has_produtos_editais1_idx` (`editais_id` ASC),
  CONSTRAINT `fk_editais_has_produtos_editais1`
    FOREIGN KEY (`editais_id`)
    REFERENCES `agrofam`.`editais` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_editais_has_produtos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `agrofam`.`produtos` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`documentos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(140) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`ofertas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produtos_id` INT(11) NOT NULL,
  `agricultores_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ofertas_produtos_idx` (`produtos_id` ASC),
  INDEX `fk_ofertas_agricultores1_idx` (`agricultores_id` ASC),
  CONSTRAINT `fk_ofertas_agricultores1`
    FOREIGN KEY (`agricultores_id`)
    REFERENCES `agrofam`.`agricultores` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ofertas_produtos`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `agrofam`.`produtos` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `agrofam`.`requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agrofam`.`requisitos` (
  `documentos_id` INT(11) NOT NULL,
  `editais_id` INT(11) NOT NULL,
  PRIMARY KEY (`documentos_id`, `editais_id`),
  INDEX `fk_documentos_has_editais_editais1_idx` (`editais_id` ASC),
  INDEX `fk_documentos_has_editais_documentos1_idx` (`documentos_id` ASC),
  CONSTRAINT `fk_documentos_has_editais_documentos1`
    FOREIGN KEY (`documentos_id`)
    REFERENCES `agrofam`.`documentos` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_documentos_has_editais_editais1`
    FOREIGN KEY (`editais_id`)
    REFERENCES `agrofam`.`editais` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `agrofam` ;

-- -----------------------------------------------------
-- procedure inserirProdutos
-- -----------------------------------------------------

DELIMITER $$
USE `agrofam`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `inserirProdutos`(IN nomeProduto varchar(45), IN subtipoProduto varchar(45))
BEGIN
	set @idSubtipo = (select id from subtipos where nome = subtipoProduto);
    insert into produtos (id, nome, subtipos_id)
    values
    (null, nomeProduto, @idSubtipo);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selecionarEditaisLocalidade
-- -----------------------------------------------------

DELIMITER $$
USE `agrofam`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selecionarEditaisLocalidade`(IN $nomeLocalidade varchar(45))
BEGIN
	SELECT editais.id, titulo, dataIni, dataFim FROM editais, instituicoes, localidades
	WHERE 
	instituicoes_id = instituicoes.id AND
	instituicoes.localidades_id = localidades.id AND
	localidades.nome = $nomeLocalidade;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selecionarEditaisProdutos
-- -----------------------------------------------------

DELIMITER $$
USE `agrofam`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selecionarEditaisProdutos`(IN $produto varchar(45))
BEGIN
	SELECT editais.id, titulo, dataIni, dataFim 
    FROM editais, demandas, produtos 
    WHERE
    editais.id = demandas.editais_id AND
    demandas.produtos_id = produtos.id AND
    produtos.nome = $produto;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selecionarOfertasProduto
-- -----------------------------------------------------

DELIMITER $$
USE `agrofam`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selecionarOfertasProduto`(IN $produto varchar(45))
BEGIN
	SELECT ofertas.* FROM ofertas, produtos 
    WHERE
    ofertas.produtos_id = produtos.id AND
    produtos.nome = $produto;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selecionarOfertasRegiao
-- -----------------------------------------------------

DELIMITER $$
USE `agrofam`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selecionarOfertasRegiao`(IN $regiao varchar(45))
BEGIN
	SELECT ofertas.* FROM localidades, ofertas, agricultores
    WHERE
    ofertas.agricultores_id = agricultores.id AND
    agricultores.localidades_id = localidades.id AND
    localidades.id = 5;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
